# Generated by Django 5.2.13 on 2026-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_connectorbatch_vmmetricsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildSnapshot',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
