# Generated by Django 5.2.13 on 2026-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_weeklyreportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimChallenge',
            fields=[
                ('bearer_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=64)),
                ('public_player_id', models.CharField(max_length=32)),
                ('question', models.JSONField()),
                ('correct_answer', models.PositiveSmallIntegerField()),
                ('remaining_questions', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verifying', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimSession',
            fields=[
                ('bearer_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=64)),
                ('public_player_id', models.CharField(max_length=32)),
                ('idle_expires_at', models.DateTimeField(db_index=True)),
                ('absolute_expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_started_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClaimData',
            fields=[
                ('public_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('snapshot_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
