/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/openapi.json': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return this OpenAPI document */
    get: operations['getOpenApiDocument']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return the current Django session bootstrap data */
    get: operations['getSession']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/server/access': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Return connection details for an approved member
     * @description The response contains the configured game-server password and must not be stored or shared.
     */
    get: operations['getServerAccess']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/snapshot': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return the latest server snapshot */
    get: operations['getSnapshot']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return sampled server metric history */
    get: operations['getHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/players': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return the player archive */
    get: operations['listPlayers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/player/{public_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return one player profile */
    get: operations['getPlayer']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/leaderboard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return player rankings */
    get: operations['getLeaderboard']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activity/heatmap': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return player activity grouped by weekday and hour */
    get: operations['getActivityHeatmap']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/world/objects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return sanitized world objects */
    get: operations['getWorldObjects']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/live-map/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return live-map polling and layer configuration */
    get: operations['getLiveMapConfig']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/live-map/catalogue': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return the immutable landmark catalogue */
    get: operations['getLiveMapCatalogue']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/live-map/players': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return players and current server status for the map */
    get: operations['getLiveMapPlayers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/live-map/objects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return world objects adapted for the map */
    get: operations['getLiveMapObjects']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/telemetry/stats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return aggregate telemetry statistics */
    get: operations['getTelemetryStats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/world/diff': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return settings that differ from vanilla defaults */
    get: operations['getWorldDiff']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/palworld/players': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Return the latest sanitized Palworld player dataset
     * @description Site-admin access is required.
     */
    get: operations['getPalworldPlayers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/player-ips': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Return stored player IP observations
     * @description Site-admin access is required.
     */
    get: operations['getAdminPlayerIps']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/palworld/info': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Return the latest sanitized server metadata
     * @description Site-admin access is required.
     */
    get: operations['getPalworldInfo']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/palworld/admin/players': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Query command targets from the Palworld REST API
     * @description Site-admin access is required.
     */
    get: operations['getPalworldAdminPlayers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/palworld/announce': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Send a server announcement
     * @description Site-admin access and Django CSRF validation are required.
     */
    post: operations['announcePalworldMessage']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/palworld/kick': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Kick a player from the game server
     * @description Site-admin access and Django CSRF validation are required.
     */
    post: operations['kickPalworldPlayer']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/palworld/ban': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Ban a player from the game server
     * @description Site-admin access and Django CSRF validation are required.
     */
    post: operations['banPalworldPlayer']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/palworld/unban': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Remove a player ban
     * @description Site-admin access and Django CSRF validation are required.
     */
    post: operations['unbanPalworldPlayer']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/guild/data': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return the latest guild and base snapshot */
    get: operations['getGuildData']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/healthz/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Return private collector health
     * @description Private ingest listener only. This path has different behavior on the public listener.
     */
    get: operations['getPrivateCollectorHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/collector/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Return detailed collector state */
    get: operations['getPrivateCollectorStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/guild/ingest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Store a minimized guild/save snapshot */
    post: operations['ingestPrivateGuildData']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Error: {
      error: string
    }
    CommandResult: {
      /** @constant */
      ok: true
    }
    /** Format: date-time */
    Timestamp: string | null
    Session: {
      authenticated: boolean
      user: components['schemas']['SessionUser'] | null
      siteAdmin: boolean
      appVersion: string
      routes: components['schemas']['SessionRoutes']
    }
    SessionUser: {
      username: string
      /** Format: email */
      email: string
    }
    SessionRoutes: {
      terms: string
      profile: string
      password: string
      members: string | null
      admin: string | null
    }
    ServerAccess: {
      host: string
      port: string
      /** @description Sensitive game-server password. */
      password: string
      address: string
      configured: boolean
    }
    Snapshot: {
      status: components['schemas']['SnapshotStatus']
      info: {
        [key: string]: unknown
      }
      metrics: {
        [key: string]: unknown
      }
      players: components['schemas']['SnapshotPlayer'][]
      settings: {
        [key: string]: unknown
      }
      events: components['schemas']['PlayerEvent'][]
      summary_24h: {
        peak_players: number
        average_players: number
        average_fps: number
        minimum_fps: number
      }
      version: string
    }
    SnapshotStatus: {
      online: boolean
      reachable: boolean
      stale: boolean
      data_age_seconds: number | null
      players_stale: boolean
      last_updated: components['schemas']['Timestamp']
      started_at: components['schemas']['Timestamp']
    }
    SnapshotPlayer: {
      id: string
      name: string
      accountName?: string
      ping?: number | null
      location_x?: number | null
      location_y?: number | null
      level?: number
      building_count?: number
      location_available: boolean
      session: {
        first_seen?: components['schemas']['Timestamp']
        last_seen?: components['schemas']['Timestamp']
        current_session?: number
        online_7d?: number
      }
    } & {
      [key: string]: unknown
    }
    History: {
      /** @enum {string} */
      range: '6h' | '24h' | '7d' | '30d' | '90d'
      window: {
        /** Format: date-time */
        from: string
        /** Format: date-time */
        to: string
      }
      fps_health: components['schemas']['FpsHealth']
      samples: components['schemas']['MetricSample'][]
    }
    FpsHealth: {
      /** @enum {string} */
      state: 'no_data' | 'calibrating' | 'stale' | 'ok'
      score: number | null
      label: string
      sample_count: number
      coverage_seconds?: number
      newest_sample_age_seconds?: number
      nominal_cadence_seconds?: number
      gap_threshold_seconds?: number
      median_fps?: number
      recent_median_fps?: number
      average_fps?: number
      under_30_percent?: number
      longest_dip_seconds?: number
      components?: {
        [key: string]: number
      }
    }
    MetricSample: {
      /** Format: date-time */
      timestamp: string
      fps: number
      fps_average: number
      frame_time: number
      players: number
      max_players: number
      bases: number
      gap_before: boolean
    }
    PlayerArchive: {
      /** Format: date-time */
      generated_at: string
      windows: components['schemas']['PlaytimeWindows']
      save_updated_at: components['schemas']['Timestamp']
      players: components['schemas']['ArchivedPlayer'][]
    }
    PlaytimeWindows: {
      month_days: number
      year_days: number
    }
    ArchivedPlayer: {
      id: string
      name: string
      accountName: string
      level: number
      building_count: number
      first_seen: components['schemas']['Timestamp']
      last_seen: components['schemas']['Timestamp']
      online: boolean
      session_count: number
      minutes_30d: number
      minutes_365d: number
      minutes_all: number
      average_session_minutes: number
      longest_session_minutes: number
      active_days_30d: number
      ping_7d?: components['schemas']['PingStats'] | null
      periods: components['schemas']['PlayerSession'][]
      save_available: boolean
      save_only: boolean
      saved_level: number | null
      exp: number | null
      owned_pal_count: number | null
      unused_status_points: number | null
      status_points: {
        [key: string]: number
      }
      guild_name: string
      is_guild_admin: boolean
    }
    PingStats: {
      average: number
      minimum: number
      maximum: number
      sample_count: number
    }
    PlayerSession: {
      /** Format: date-time */
      started_at: string
      ended_at: components['schemas']['Timestamp']
      active: boolean
      duration_minutes: number
    }
    PlayerDetail: {
      player: components['schemas']['PlayerProfile']
      sessions: components['schemas']['PlayerSession'][]
      ping: components['schemas']['PingSample'][]
      presence: components['schemas']['PresenceGrid']
      events: components['schemas']['PlayerEvent'][]
      /** Format: date-time */
      generated_at: string
    }
    PlayerProfile: {
      public_id: string
      name: string
      account_name: string
      level: number
      building_count: number
      /** Format: date-time */
      first_seen: string
      /** Format: date-time */
      last_seen: string
      online: boolean
      current_session: number | null
      minutes_lifetime: number
      session_count_lifetime: number
      longest_session_minutes: number
    }
    PingSample: {
      /** Format: date-time */
      timestamp: string
      ping: number
    }
    PresenceGrid: {
      weeks: number
      /** @constant */
      rows: 7
      /** @constant */
      cols: 24
      grid: number[][]
    }
    PlayerEvent: {
      type: string
      player?: string
      player_id?: string
      /** Format: date-time */
      timestamp: string
    }
    Leaderboard: {
      /** Format: date-time */
      generated_at: string
      windows: components['schemas']['PlaytimeWindows']
      by_playtime: {
        '30d': components['schemas']['LeaderboardPlayer'][]
        '365d': components['schemas']['LeaderboardPlayer'][]
        all: components['schemas']['LeaderboardPlayer'][]
      }
      by_level: components['schemas']['LeaderboardPlayer'][]
      total_players: number
    }
    LeaderboardPlayer: {
      id: string
      name: string
      account_name: string
      level: number
      /** Format: date-time */
      first_seen: string
      /** Format: date-time */
      last_seen: string
      online: boolean
      minutes_30d: number
      minutes_365d: number
      minutes_all: number
    }
    ActivityHeatmap: {
      /** Format: date-time */
      generated_at: string
      /** @enum {string} */
      range: '7d' | '30d' | '90d'
      weekday_labels: string[]
      grid: number[][]
      hour_totals: number[]
      day_totals: number[]
      peak_hour: number | null
      peak_day: string | null
      session_count: number
      total_minutes: number
    }
    WorldObjects: {
      available: boolean
      objects: {
        [key: string]: unknown
      }[]
      count: number
      source_count: number
      supported_count: number
      source_counts: {
        [key: string]: number
      }
      active_counts: {
        [key: string]: number
      }
      kind_counts: {
        [key: string]: number
      }
      omitted_counts: {
        [key: string]: number
      }
      truncated: boolean
      stale: boolean
      updated_at: components['schemas']['Timestamp']
    }
    LiveMapConfig: {
      pollIntervalMs: number
      worldPollIntervalMs: number
      worldDataEnabled: boolean
      layers: components['schemas']['MapLayer'][]
      catalogueUrl: string
      landmarks: components['schemas']['MapLocation'][]
      landmarkCatalogue: components['schemas']['CatalogueMetadata']
      upstreamRevision: string
    }
    MapLayer: {
      id: string
      name: string
      imageUrl: string
      bounds: number[]
    }
    CatalogueMetadata: {
      gameVersion: string
      generator: string
      decoder: string
    }
    LiveMapCatalogue: {
      gameVersion: string
      generator: string
      decoder: string
      locations: components['schemas']['MapLocation'][]
    }
    MapLocation: {
      id: string
      kind: string
      name: string
      detail?: string
      level?: number
      x: number
      y: number
      map: string
    }
    LiveMapPlayers: {
      server: {
        name: string
        description: string
        version: string
      }
      metrics: {
        currentPlayers: number
        maxPlayers: number
        serverFps: number
        serverFrameTime: number
        uptimeSeconds: number
        baseCount: number
        days: number
      }
      metricsAvailable: boolean
      metricsStale: boolean
      connected: boolean
      stale: boolean
      saveEnabled: boolean
      saveAvailable: boolean
      saveStale: boolean
      /** Format: date-time */
      metricsUpdatedAt?: string
      /** Format: date-time */
      lastSuccessAt?: string
      /** Format: date-time */
      saveUpdatedAt?: string
      /** Format: date-time */
      saveSnapshotAt?: string
      players: components['schemas']['LiveMapPlayer'][]
    }
    LiveMapPlayer: {
      id: string
      name: string
      level: number
      online: boolean
      /** Format: date-time */
      lastSeenAt: string
      x: number
      y: number
      map: string
      guildKey?: string
      guildName?: string
    }
    LiveMapObjects: {
      enabled: boolean
      available: boolean
      stale: boolean
      unsupported: boolean
      truncated: boolean
      total: number
      /** Format: date-time */
      updatedAt?: string
      lastError?: string
      objects: components['schemas']['LiveMapObject'][]
    }
    LiveMapObject: {
      id: string | null
      kind: string
      name: string
      x: number
      y: number
      map: string
      detail?: string
      baseId?: string
      guildKey?: string
      guildName?: string
      level?: number
      ownerId?: string
    }
    TelemetryStats: {
      /** Format: date-time */
      generated_at: string
      uptime: {
        [key: string]: unknown
      }
      fps: {
        [key: string]: unknown
      }
      players: {
        [key: string]: unknown
      }
      world: {
        [key: string]: unknown
      }
      data_age_threshold_seconds: number
    }
    WorldDiff: {
      /** Format: date-time */
      generated_at: string
      diffs: {
        key: string
        vanilla: unknown
        current: unknown
      }[]
      total: number
      has_settings: boolean
    }
    PalworldPlayers: {
      available: boolean
      players: {
        [key: string]: unknown
      }[]
      generated_at: components['schemas']['Timestamp']
      stale: boolean
    }
    AdminPlayerIps: {
      players: {
        name: string
        account_name: string
        ip: string
        observed_at: components['schemas']['Timestamp']
        /** Format: date-time */
        last_seen: string
        online: boolean
      }[]
    }
    PalworldInfo: {
      available: boolean
      generated_at: components['schemas']['Timestamp']
      stale: boolean
    } & {
      [key: string]: unknown
    }
    AdminCommandPlayers: {
      players: {
        userId: string
        name: string
        level: number
        ping: number
        location_x: number
        location_y: number
      }[]
    }
    AnnouncementCommand: {
      message: string
    }
    PlayerCommand: {
      userid: string
    }
    GuildData: {
      schema_version: number
      guilds: components['schemas']['Guild'][]
      bases: components['schemas']['GuildBase'][]
      world: {
        [key: string]: number
      }
      updated_at: components['schemas']['Timestamp']
      stale: boolean
      alerts?: components['schemas']['GuildAlert'][]
    }
    GuildAlert: {
      /** @enum {string} */
      level: 'warning' | 'danger'
      title: string
      detail: string
    }
    CollectorHealth: {
      /** @enum {string} */
      status: 'ok' | 'starting'
      collector: string
      version: string
    }
    CollectorStatus: {
      state: string
      started_at: components['schemas']['Timestamp']
      heartbeat: components['schemas']['Timestamp']
      datasets: {
        [key: string]: unknown
      }
    }
    GuildIngest: {
      /** @enum {integer} */
      schema_version: 2 | 3
      guilds: components['schemas']['Guild'][]
      bases: components['schemas']['GuildBase'][]
      players?: components['schemas']['SavedPlayer'][]
      world: components['schemas']['GuildWorld']
      diagnostics: components['schemas']['GuildDiagnostics']
    } & unknown
    Guild: {
      group_id: string
      guild_name: string
      players: {
        player_name: string
        is_admin: boolean
      }[]
      base_count?: number
      pal_count?: number
      worker_count?: number
      working_count?: number
      problem_worker_count?: number
      active_raid_count?: number
    }
    GuildBase: {
      base_id: string
      group_id: string
      name: string
      location_x: number
      location_y: number
      worker_count?: number
      working_count?: number
      sick_count?: number
      hungry_count?: number
      low_sanity_count?: number
      problem_worker_count?: number
      raid_active: boolean
      work_types: {
        key: string
        count: number
      }[]
    }
    SavedPlayer: {
      player_id: string
      player_name: string
      guild_id: string
      is_admin: boolean
      level: number
      exp: number
      owned_pal_count: number
      unused_status_points: number
      status_points: {
        max_hp?: number
        stamina?: number
        attack?: number
        carry_weight?: number
        capture_rate?: number
        work_speed?: number
      }
    }
    GuildWorld: {
      active_raid_count?: number
      oil_rig_count?: number
      oil_rig_alert_count?: number
      oil_rig_cleared_count?: number
    }
    GuildDiagnostics: {
      unowned_base_count?: number
      missing_worker_container_count?: number
      unresolved_worker_count?: number
    }
  }
  responses: {
    /** @description Command accepted */
    CommandAccepted: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['CommandResult']
      }
    }
    /** @description Invalid request */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Authentication is missing or invalid */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The authenticated account cannot perform this operation */
    Forbidden: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Request body exceeds the private API limit */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Content-Type must be application/json */
    UnsupportedMediaType: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description JSON payload failed schema validation */
    UnprocessableEntity: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The Palworld REST API could not complete the command */
    UpstreamError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Required private API configuration is unavailable */
    ServiceUnavailable: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
  }
  parameters: {
    HistoryRange: '6h' | '24h' | '7d' | '30d' | '90d'
    ActivityRange: '7d' | '30d' | '90d'
    PlayerPublicId: string
    IfNoneMatch: string
  }
  requestBodies: {
    PlayerCommand: {
      content: {
        'application/json': components['schemas']['PlayerCommand']
      }
    }
  }
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getOpenApiDocument: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OpenAPI 3.1 document */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Authenticated session and account routes */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Session']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getServerAccess: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Connection details. Sent with Cache-Control: no-store, private. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerAccess']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getSnapshot: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Latest sanitized server state */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Snapshot']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getHistory: {
    parameters: {
      query?: {
        range?: components['parameters']['HistoryRange']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Metric history for the selected window */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['History']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  listPlayers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Player archive with telemetry and save progression */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerArchive']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getPlayer: {
    parameters: {
      query?: never
      header?: never
      path: {
        public_id: components['parameters']['PlayerPublicId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Player profile, sessions, ping and presence */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerDetail']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  getLeaderboard: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Playtime and level rankings */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Leaderboard']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getActivityHeatmap: {
    parameters: {
      query?: {
        range?: components['parameters']['ActivityRange']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Activity heatmap */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityHeatmap']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getWorldObjects: {
    parameters: {
      query?: never
      header?: {
        'If-None-Match'?: components['parameters']['IfNoneMatch']
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description World object dataset */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorldObjects']
        }
      }
      /** @description Dataset has not changed */
      304: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getLiveMapConfig: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Live-map configuration */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LiveMapConfig']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getLiveMapCatalogue: {
    parameters: {
      query?: {
        /** @description SHA-256 catalogue version returned by the config endpoint */
        v?: string
      }
      header?: {
        'If-None-Match'?: components['parameters']['IfNoneMatch']
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Landmark catalogue */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LiveMapCatalogue']
        }
      }
      /** @description Catalogue has not changed */
      304: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getLiveMapPlayers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Live-map player state */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LiveMapPlayers']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getLiveMapObjects: {
    parameters: {
      query?: never
      header?: {
        'If-None-Match'?: components['parameters']['IfNoneMatch']
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Live-map object state */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LiveMapObjects']
        }
      }
      /** @description Dataset has not changed */
      304: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getTelemetryStats: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Telemetry aggregates */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TelemetryStats']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getWorldDiff: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current settings differences */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorldDiff']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getPalworldPlayers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Latest stored player dataset */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PalworldPlayers']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getAdminPlayerIps: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Player IP observations */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminPlayerIps']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getPalworldInfo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Latest server metadata */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PalworldInfo']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getPalworldAdminPlayers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current command targets */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminCommandPlayers']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      502: components['responses']['UpstreamError']
    }
  }
  announcePalworldMessage: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AnnouncementCommand']
      }
    }
    responses: {
      200: components['responses']['CommandAccepted']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      415: components['responses']['UnsupportedMediaType']
      502: components['responses']['UpstreamError']
    }
  }
  kickPalworldPlayer: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['PlayerCommand']
    responses: {
      200: components['responses']['CommandAccepted']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      415: components['responses']['UnsupportedMediaType']
      502: components['responses']['UpstreamError']
    }
  }
  banPalworldPlayer: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['PlayerCommand']
    responses: {
      200: components['responses']['CommandAccepted']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      415: components['responses']['UnsupportedMediaType']
      502: components['responses']['UpstreamError']
    }
  }
  unbanPalworldPlayer: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['PlayerCommand']
    responses: {
      200: components['responses']['CommandAccepted']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      415: components['responses']['UnsupportedMediaType']
      502: components['responses']['UpstreamError']
    }
  }
  getGuildData: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Guild snapshot. Admin users additionally receive alerts. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GuildData']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
    }
  }
  getPrivateCollectorHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Collector is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CollectorHealth']
        }
      }
      /** @description Collector is starting or unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CollectorHealth']
        }
      }
    }
  }
  getPrivateCollectorStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Collector runtime state */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CollectorStatus']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  ingestPrivateGuildData: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GuildIngest']
      }
    }
    responses: {
      200: components['responses']['CommandAccepted']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      413: components['responses']['PayloadTooLarge']
      415: components['responses']['UnsupportedMediaType']
      422: components['responses']['UnprocessableEntity']
      503: components['responses']['ServiceUnavailable']
    }
  }
}
